#!/bin/sh

prog=/usr/bin/cotp

conf_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/cotp-wrap"

# default db path
DB_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/cotp"

#config file
config_file="${conf_dir}/configrc"

if [ -r "$config_file" ]; then
    . "$config_file"
else
    if [ ! -d "$conf_dir" ]; then
        mkdir -p "$conf_dir"
    fi
    cat << __HEREDOC__ > "$config_file"
# vim: ft=sh
# cotp-wrap config file

# default base path for db.cotp
DB_PATH="$DB_PATH"
__HEREDOC__
fi

export COTP_DB_PATH="$DB_PATH/db.cotp"

get_password_from_keyring() {
    secret-tool lookup application authenticator
}

get_password_from_keyring | $prog --password-stdin "$@"
