#!/bin/sh

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/rofi-askpass/config.rasi"

def_prompt="password"

PROMPT="${1:-$def_prompt}"

rofi -dmenu \
     -password \
     -no-fixed-num-lines \
     -lines 0 \
     -theme "$CONFIG" \
     -theme-str "textbox-prompt-colon { str: \"$PROMPT\"; }"
