#!/bin/sh


if [ "$#" -eq 0 ]; then
    printf '%s\n' "no arguments provided!"
    return 1
fi

qr_file="$1"

decoded_qr="$(zbarimg -q "$qr_file" | cut -d':' -f2-)"
sleep 2
xdotool type --delay 6 "$decoded_qr"
notify-send -i nwg-clipman "clipboard selection typed"
